const cropMoistureData = [
    {"cropname": "Alfalfa", "low": 0.2, "high": 0.35, "description": "Prefers consistent moisture, especially during regrowth periods."}, 
    {"cropname": "Almonds", "low": 0.15, "high": 0.25, "description": "Moderately drought-tolerant, requires steady moisture during nut set."}, 
    {"cropname": "Pistachios", "low": 0.15, "high": 0.25, "description": "Moderately drought-tolerant, requires steady moisture during nut set."}, 
    {"cropname": "Citrus", "low": 0.18, "high": 0.28, "description": "Requires good soil moisture to support fruit development."}, 
    {"cropname": "Subtropical", "low": 0.18, "high": 0.28, "description": "Requires good soil moisture to support fruit development."}, 
    {"cropname": "Corn", "low": 0.22, "high": 0.32, "description": "Needs ample moisture during silking and tasseling stages."}, 
    {"cropname": "Cotton", "low": 0.15, "high": 0.25, "description": "Tolerates dry conditions but needs moisture during flowering."}, 
    {"cropname": "Cucurbits", "low": 0.2, "high": 0.3, "description": "Sensitive to moisture stress, especially during fruiting."}, 
    {"cropname": "Dry Beans", "low": 0.18, "high": 0.28, "description": "Moderate moisture needs, avoid excess water at maturity."}, 
    {"cropname": "Field", "low": 0.2, "high": 0.3, "description": "General field crops benefit from consistent soil moisture."}, 
    {"cropname": "Grain", "low": 0.2, "high": 0.3, "description": "Moisture critical during flowering and grain fill."}, 
    {"cropname": "Onions", "low": 0.18, "high": 0.3, "description": "Shallow roots need consistent moisture, especially during bulb formation."}, 
    {"cropname": "Garlic", "low": 0.18, "high": 0.3, "description": "Shallow roots need consistent moisture, especially during bulb formation."}, 
    {"cropname": "Other Deciduous", "low": 0.18, "high": 0.28, "description": "Fruit trees require moderate to high moisture during growth."}, 
    {"cropname": "Pasture", "low": 0.2, "high": 0.35, "description": "High water needs for dense growth, especially in hot weather."}, 
    {"cropname": "Potatoes", "low": 0.2, "high": 0.3, "description": "Even soil moisture is critical to prevent disease and tuber defects."}, 
    {"cropname": "Rice", "low": 0.3, "high": 0.45, "description": "Typically grown in saturated or flooded fields, very high moisture needs."}, 
    {"cropname": "Safflower", "low": 0.12, "high": 0.22, "description": "Drought-tolerant, low water use, suited for dry regions."}, 
    {"cropname": "Sugar Beets", "low": 0.18, "high": 0.28, "description": "Uniform moisture promotes root growth and sugar content."}, 
    {"cropname": "Tomato Fresh", "low": 0.2, "high": 0.3, "description": "Consistent moisture needed to prevent cracking and promote quality."}, 
    {"cropname": "Tomato Processing", "low": 0.2, "high": 0.3, "description": "Same moisture range as fresh tomatoes for best results."}, 
    {"cropname": "Truck Crops", "low": 0.2, "high": 0.3, "description": "Mixed vegetables generally need consistent moisture."}, 
    {"cropname": "Vineyard", "low": 0.12, "high": 0.22, "description": "Prefers drier soils for concentrated fruit, irrigation critical during fruit set."}];