export type RootStackParamList = {
  Welcome: undefined;
  SignIn: undefined;
  SignUp: undefined;
  Home: undefined;
  PlotDetails: { plotId?: number; plot?: any };
  Weather: undefined;
  Account: undefined;
  Chat: undefined;
  Plots: undefined;
  PlotSettings: { plotId?: string };
  SpecificDay: { plotId?: number; day?: string; date?: string };
  Marketplace: undefined;
  Analytics: undefined;
  Reports: undefined;
  ExportReports: undefined;
  PredictiveDashboard: undefined;
  AnomalyAlerts: undefined;
  PlantHealthScanner: undefined;
  YieldForecast: undefined;
  SmartMap: undefined;
  Community: undefined;
  SetupPlot: undefined;
  OnboardingLocation: { plotName?: string; selectedCrop?: string; cropDetails?: any };
  OnboardingComplete: { plotName?: string; selectedCrop?: string; cropDetails?: any; latitude?: number; longitude?: number; address?: string };
  TermsOfService: undefined;
  PrivacyPolicy: undefined;
  NotificationSettings: undefined;
  Help: undefined;
  Subscription: undefined;
  ForgotPassword: undefined;
  Calendar: { plotId?: number };
  AddSchedule: { plotId?: number };
  ScheduleSettings: { plotId?: number };
  ScheduleAnalytics: { plotId?: number };
  ExportSchedule: { plotId?: number };
};

export type MainTabParamList = {
  Home: undefined;
  Plots: undefined;
  Weather: undefined;
  Account: undefined;
}; 